---
kind: pipeline
name: default
type: kubernetes
steps:
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    tags:
      - latest
      - build-v${DRONE_BUILD_NUMBER}
    repo: 659994610574.dkr.ecr.us-east-1.amazonaws.com/tomcat
    registry: 659994610574.dkr.ecr.us-east-1.amazonaws.com/
    
- name: kubernetes_deploy
  image: ramalingam81/aws-kubectl-helm-kops
  environment:
    KOPS_STATE_STORE: "s3://kops.onthecloud.ga"
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    AWS_DEFAULT_REGION: us-east-1
  commands:
    - export KOPS_STATE_STORE=s3://kops.onthecloud.ga && kops export kubeconfig --name kops.onthecloud.ga --admin
    - chmod +x /root/.kube/config
#    - kubectl create ns tvm
    - sed -i 's/latest/build-v${DRONE_BUILD_NUMBER}/g' kubernetes/deployment.yaml
    - kubectl apply -f kubernetes/deployment.yaml 
